import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slider from '../comps/Slider' 
import PizzaList from '../comps/PizzaList'
import axios from 'axios'

export default function Home({ pizzaList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <PizzaList pizzaList={ pizzaList } />
      homepage
    </div>
  )
}

export const getServerSideProps = async() => {
  const res = await axios.get('http://localhost:3000/api/product')
  return {
    props: {
      pizzaList: res.data
    }
  }
}
